// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_decoupled_sum
double compute_decoupled_sum(List x, List y, Function kernel_function, bool symmetric);
RcppExport SEXP _UStatDecouple_compute_decoupled_sum(SEXP xSEXP, SEXP ySEXP, SEXP kernel_functionSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< Function >::type kernel_function(kernel_functionSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_decoupled_sum(x, y, kernel_function, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// compute_multiple_decoupled_sums
NumericVector compute_multiple_decoupled_sums(List x, List y_list, Function kernel_function, bool symmetric);
RcppExport SEXP _UStatDecouple_compute_multiple_decoupled_sums(SEXP xSEXP, SEXP y_listSEXP, SEXP kernel_functionSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< Function >::type kernel_function(kernel_functionSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_multiple_decoupled_sums(x, y_list, kernel_function, symmetric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UStatDecouple_compute_decoupled_sum", (DL_FUNC) &_UStatDecouple_compute_decoupled_sum, 4},
    {"_UStatDecouple_compute_multiple_decoupled_sums", (DL_FUNC) &_UStatDecouple_compute_multiple_decoupled_sums, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_UStatDecouple(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
