# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_decoupled_sum <- function(x, y, kernel_function, symmetric) {
    .Call(`_UStatDecouple_compute_decoupled_sum`, x, y, kernel_function, symmetric)
}

compute_multiple_decoupled_sums <- function(x, y_list, kernel_function, symmetric) {
    .Call(`_UStatDecouple_compute_multiple_decoupled_sums`, x, y_list, kernel_function, symmetric)
}

